pipelines:
- pipelineName: de_kpm_analysis
  pipelineDescription: "Differential protein expression analysis and KPM analysis. Given a biological network and a set of case-control studies, KeyPathwayMiner efficiently extracts all maximal connected sub-networks. These sub-networks contain the entities that are mainly dysregulated, e.g., differentially expressed, in most cases studied."
  pipelineCommand: nextflow run
  pipelineVersion: "1.0.0"

  pipelineParams:
  - paramName: Output Folder Path
    paramKey: --output
    paramDescription: Output folder path to store the result
    paramType: OutputPath
    isMultiValue: false
    isRequired: true

  - paramName: Count Files
    paramDescription: List of count files
    paramKey: --count_files
    paramType: InputPath
    isMultiValue: true
    isRequired: true

  - paramName: Metadata JSON File Path
    paramDescription: file path for the meta data json file
    paramKey: --meta_file
    paramType: InputPath
    isMultiValue: false
    isRequired: true