pipelines:
- pipelineName: de_analysis_repository_based
  pipelineDescription: "Differential protein expression analysis and KPM analysis. Given a biological network and a set of case-control studies, KeyPathwayMiner efficiently extracts all maximal connected sub-networks. These sub-networks contain the entities that are mainly dysregulated, e.g., differentially expressed, in most cases studied."
  pipelinePath: $PIPELINE_PATH/main.nf
  pipelineCommand: nextflow run
  pipelineVersion: "1.2.0"

  pipelineParams:
  - paramName: Output Folder Path
    paramKey: --output
    paramDescription: Output folder path to store the result
    paramType: OutputPath
    isMultiValue: false
    isRequired: true

  - paramName: Count Files
    paramDescription: List of count files
    paramKey: --count_files
    paramType: InputPath
    isMultiValue: true
    isRequired: true

  - paramName: Metadata JSON File Path
    paramDescription: file path for the meta data json file
    paramKey: --meta_file
    paramType: InputPath
    isMultiValue: false
    isRequired: true

  - paramName: Threshold for adjusted p-values or p-values
    paramDescription: Threshold for adjusted p-values or p-values
    paramKey: --alpha
    paramType: Number
    isMultiValue: false
    isRequired: false

  - paramName: Organism
    paramDescription: "Organism of genes in gene column ('human' or 'rat')."
    paramKey: --organism
    paramType: Text
    isMultiValue: false
    isRequired: false

  - paramName: Differential Expression
    paramDescription:  Apply differential Expression Analysis.
    paramKey: --de_analysis
    paramType: Boolean
    isMultiValue: false
    isRequired: false

  - paramName: Key Pathway Miner
    paramDescription:  Apply Key Pathway Miner Analysis.
    paramKey: --kpm_analysis
    paramType: Boolean
    isMultiValue: false
    isRequired: false

  - paramName: GO Enrichment
    paramDescription:  Apply GO Enrichment Analysis.
    paramKey: --go_enrichment
    paramType: Boolean
    isMultiValue: false
    isRequired: false

  - paramName: Network Enrichment and Drug Repurposing
    paramDescription:  Apply Network Enrichment and Drug Repurposing Analysis.
    paramKey: --network_enrichment
    paramType: Boolean
    isMultiValue: false
    isRequired: false

- pipelineName: de_analysis_repository_based
  pipelineDescription: "Differential protein expression analysis and KPM analysis. Given a biological network and a set of case-control studies, KeyPathwayMiner efficiently extracts all maximal connected sub-networks. These sub-networks contain the entities that are mainly dysregulated, e.g., differentially expressed, in most cases studied."
  pipelinePath: $PIPELINE_PATH/main.nf
  pipelineCommand: nextflow run
  pipelineVersion: "1.3.0"

  pipelineParams:
  - paramName: Output Folder Path
    paramKey: --output
    paramDescription: Output folder path to store the result
    paramType: OutputPath
    isMultiValue: false
    isRequired: true

  - paramName: Count Files
    paramDescription: List of count files
    paramKey: --count_files
    paramType: InputPath
    isMultiValue: true
    isRequired: true

  - paramName: Metadata JSON File Path
    paramDescription: file path for the meta data json file
    paramKey: --meta_file
    paramType: InputPath
    isMultiValue: false
    isRequired: true

  - paramName: Threshold for adjusted p-values or p-values
    paramDescription: Threshold for adjusted p-values or p-values
    paramKey: --alpha
    paramType: Number
    isMultiValue: false
    isRequired: false

  - paramName: Organism
    paramDescription: "Organism of genes in gene column ('human' or 'rat')."
    paramKey: --organism
    paramType: Text
    isMultiValue: false
    isRequired: false

  - paramName: Condition 1
    paramDescription: Set to 'default' if you don't want to change the default (timepoint)
    paramKey: --condition_1
    paramType: Text
    isMultiValue: true
    isRequired: false

  - paramName: Condition 2
    paramDescription: Set to 'default' if you don't want to change the default (strain)
    paramKey: --condition_2
    paramType: Text
    isMultiValue: true
    isRequired: false

  - paramName: Condition 3
    paramDescription: Set to 'default' if you don't want to change the default (location)
    paramKey: --condition_3
    paramType: Text
    isMultiValue: true
    isRequired: false



  - paramName: Differential Expression
    paramDescription:  Apply differential Expression Analysis.
    paramKey: --de_analysis
    paramType: Boolean
    isMultiValue: false
    isRequired: false

  - paramName: Key Pathway Miner
    paramDescription:  Apply Key Pathway Miner Analysis.
    paramKey: --kpm_analysis
    paramType: Boolean
    isMultiValue: false
    isRequired: false

  - paramName: GO Enrichment
    paramDescription:  Apply GO Enrichment Analysis.
    paramKey: --go_enrichment
    paramType: Boolean
    isMultiValue: false
    isRequired: false

  - paramName: Network Enrichment and Drug Repurposing
    paramDescription:  Apply Network Enrichment and Drug Repurposing Analysis.
    paramKey: --network_enrichment
    paramType: Boolean
    isMultiValue: false
    isRequired: false